name: Run Robot Framework Tests
on:
  push:
    # runs tests for commits pushed to master
    branches:
        main
jobs:
    run_tests:
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout
          uses: actions/checkout@v2
        - name: Robot Framework
          uses: joonvena/robotframework-docker-action@v1.0
          
          
