name: "run-test"
on:
    push:
      branches: main

jobs:
  
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
         
      - name: Robot Framework
        uses: mehmetaydogmus/github-actions-test@v1.0.0
        
