
name: "run-test"

on:
  push:
    branches:
        main
jobs:

  robot_test:
    
      runs-on: ubuntu-latest
      name: Run Robot Framework Tests
      
      steps:
         - name: Checkout
           uses: mehmetaydogmus/github-actions-test@v0.0
           with:      
             tests_dir: '${{ github.workspace }}'

         - name: Robot Framework
           uses: joonvena/robotframework-docker-action@v1.0
           
           
